services:
  database:
    container_name: sc2006-db
    image: mysql:8.0.34
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    command:
      - '--skip-log-bin'
    ports:
      - 3306:3306
    volumes:
      - ./database:/docker-entrypoint-initdb.d
      - db-volume:/var/lib/mysql
    healthcheck:
      test:
        [
          "CMD",
          "mysqladmin",
          "ping",
          "-h",
          "localhost",
          "-u",
          "${DB_USER}",
          "-p${DB_PASSWORD}",
        ]
      interval: 10s
      timeout: 20s
      retries: 10
  database-updater:
    container_name: sc2006-db-updater
    build: ./database-updater
    depends_on:
      database:
        condition: service_healthy
    environment:
      DB_HOST: database
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_DATABASE: ${DB_DATABASE}
      DB_UPDATER_AVAILABILITY_FREQUENCY: ${DB_UPDATER_AVAILABILITY_FREQUENCY}
      DB_UPDATER_PRICE_FREQUENCY: ${DB_UPDATER_PRICE_FREQUENCY}
      DB_UPDATER_LTA_KEY: ${DB_UPDATER_LTA_KEY}
      DB_UPDATER_URA_KEY: ${DB_UPDATER_URA_KEY}

    volumes:
      - ./database-updater:/var/www/db-updater
  api:
    container_name: sc2006-api
    build: ./api
    depends_on:
      database:
        condition: service_healthy
    ports:
      - 8080:8080
    environment:
      API_PORT: ${API_PORT}
      DB_HOST: database
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_DATABASE: ${DB_DATABASE}
      DB_UPDATER_LTA_KEY: ${DB_UPDATER_LTA_KEY}
      DB_UPDATER_URA_KEY: ${DB_UPDATER_URA_KEY}
      GOOGLE_MAPS_KEY: ${GOOGLE_MAPS_KEY}
    volumes:
      - ./api:/var/www/api
volumes:
  db-volume:
